project:
  type: website

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Talks"
        file: talks.qmd
      - text: "About"
        file: about.qmd 
    right:
      - icon: twitter
        href: https://twitter.com/renata_mh
      - icon: github
        href: https://github.com/rmhirota

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
