project:
  type: website

website:
  title: "Renata Hirota"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - talks.qmd
      - about.qmd 
    tools:
      - icon: twitter
        href: https://twitter.com/renata_mh
      - icon: github
        href: https://github.com/rmhirota

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



