project:
  type: website

website:
  open-graph: true
  navbar:
    background: primary
    search: true
    image: _site/profile.jpg
    left:
      - text: "Home"
        file: index.qmd
      - text: "Talks"
        file: talks.qmd
      - text: "Awards"
        file: awards.qmd
    right:
      - text: "Blog"
        file: blog.qmd
      - text: About
        file: about.qmd

format:
  html:
    theme: journal  # simplex yeti
    css: styles.css
    toc: false
